---

name: ci

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

      matrix:
        ruby: [2.7.1, 2.6.6]

        deps: ["rails_60"]

    steps:
      - uses: actions/checkout@v2

      - name: Download Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.8.0-linux-amd64 > bin/test-reporter
          chmod +x bin/test-reporter

      - name: Set Gemfile (default)
        run: echo "BUNDLE_GEMFILE=Gemfile" >> $GITHUB_ENV
        if: matrix.deps == 'rails_60'

      - name: Set Gemfile (alternative)
        run: echo "BUNDLE_GEMFILE=gemfiles/${{ matrix.deps }}/Gemfile" >> $GITHUB_ENV
        if: matrix.deps != 'rails_60'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup git
        run: |
          git config --global user.email activeadmin@ci.dummy
          git config --global user.name ActiveAdmin

      - name: Create test app
        run: COVERAGE=true PARALLEL_TEST_PROCESSORS=4 bin/rake setup

      - name: Run RSpec tests
        run: |
          COVERAGE=true PARALLEL_TEST_PROCESSORS=4 PARALLEL_TEST_HEARTBEAT_INTERVAL=3600 bin/parallel_rspec spec/
          COVERAGE=true RSPEC_FILESYSTEM_CHANGES=true bin/rspec

      - name: Run Cucumber features
        run: |
          COVERAGE=true PARALLEL_TEST_PROCESSORS=4 PARALLEL_TEST_HEARTBEAT_INTERVAL=3600 bin/parallel_cucumber features/
          COVERAGE=true bin/cucumber --profile filesystem-changes
          COVERAGE=true bin/cucumber --profile class-reloading

      - name: Format coverage
        run: |
          bin/prepare_coverage
          bin/test-reporter format-coverage --output coverage/codeclimate.${{ matrix.ruby }}.${{ matrix.deps }}.json

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: tmp/test_apps/${{ matrix.deps }}/tmp/capybara

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: codeclimate.{{ matrix.ruby }}.{{ matrix.deps }}.json

  upload_coverage:
    runs-on: ubuntu-20.04

    needs: test

    env:
      CC_TEST_REPORTER_ID: 8d5fcf7abea6d56c625104a9d1a81140a588a7f546f4fa9de9bc6ffc8feaaf70

    steps:
      - name: Download Code Climate test-reporter
        run: |
          mkdir bin
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.8.0-linux-amd64 > bin/test-reporter
          chmod +x bin/test-reporter

      - uses: actions/download-artifact@v2
        with:
          name: coverage

      - name: Upload coverage results to Code Climate
        run: |
          bin/test-reporter sum-coverage coverage/codeclimate.*.json
          bin/test-reporter upload-coverage
